# Production (основной сайт)
[context.production]
  [[redirects]]
    from = "/*"
    to = "https://artmarketprint.by/:splat"
    status = 301
    force = true

# Для develop-ветки
[context.deploy-preview]
  [[redirects]]
    from = "/*"
    to = "https://artmarketprint.by/:splat"
    status = 301
    force = true
