[[redirects]]
from = "https://develop--artmarketprint.netlify.app/*"
to = "https://artmarketprint.by/:splat"
status = 301
force = true

[[redirects]]
from = "https://artmarketprint.netlify.app/*"
to = "https://artmarketprint.by/:splat"
status = 301
force = true
