import { SERVICES_QUERY } from './service.query';
import { CATEGORIES_QUERY } from './category.query';
import { PROJECTS_QUERY, PROJECTS_BY_SERVICE_QUERY, PROJECTS_BY_CATEGORY_QUERY, PROJECT_QUERY, PROJECT_SLUGS_QUERY, } from './project.query';
import { NAVIGATION_QUERY, HERO_QUERY } from './page.query';

export {
  SERVICES_QUERY,
  CATEGORIES_QUERY,
  PROJECTS_QUERY,
  PROJECTS_BY_SERVICE_QUERY,
  PROJECTS_BY_CATEGORY_QUERY,
  PROJECT_QUERY,
  PROJECT_SLUGS_QUERY,
  NAVIGATION_QUERY,
  HERO_QUERY
}